# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3b2774049ba7275b5644f5d9061bd454ebdbf7aeebb25078601b92a9d591d2fb9d29fa1fd3949c26d8735a552591a046a69dd15d5687e2d5980d3bbf967537
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>


test:
  secret_key_base: 989232ac29dfdf9859a4871d5a2a8b7b008eff378ca5848afb33829bf603477e4038980a03d31f2c2aa59f88d07259f432e88a7bb73bf91de38d0d6149b02494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
